#!/bin/bash
# UTM Configuration Script
# This script helps configure UTM for RustOS

KERNEL_PATH="/Users/justin/Downloads/Rustos-main/target/x86_64-rustos/debug/bootimage-rustos.bin"

echo "=== UTM Configuration for RustOS ==="
echo ""
echo "IMPORTANT: Follow these steps in UTM to boot your kernel:"
echo ""
echo "1. Create New Virtual Machine"
echo "   • Select 'Emulate' (not Virtualize)"
echo "   • Choose 'Other' as operating system"
echo ""
echo "2. System Configuration"
echo "   • Architecture: x86_64"
echo "   • Machine: Q35 (not PC or i440FX)"
echo "   • CPU: Nehalem or qemu64"
echo "   • Memory: 256 MB"
echo ""
echo "3. Boot Configuration"
echo "   • Enable 'Use raw kernel and initrd'"
echo "   • Kernel Path: $KERNEL_PATH"
echo "   • Leave Kernel Args empty"
echo ""
echo "4. Display Configuration"
echo "   • Display: VGA (recommended)"
echo "   • Or: Console (for serial output)"
echo ""
echo "5. Start the VM"
echo ""
echo "Your kernel should display:"
echo "   RustOS - Multiboot Kernel Started!"
echo "   ======================================"
echo "   Boot information received successfully"
echo "   System ready for operation"
echo ""
echo "Press any key to continue..."
read
